const messages = {
  en: {
    welcome_message:'welcome',
    thankyou_message:'thank you',
    menu: 'Home | Our Services | About Us',
    menu2: 'Order | Contact Us | Login',
    menu3: 'Logout | Sign Up',
    footer: 'Mistri Mama Office | Services | Company ',
    footer1: 'Discover',
    address: 'Head Office: UCEP Cheyne Tower (3rd Floor), 25, Segunbagicha, Ramna, Dhaka, PO : 1000 | Business Office: Sky View Ocean Tower (1st floor), 38 Segunbagicha, Dhaka, Bangladesh ',
    phone:'8809610-222-111',
    Office_time: ' Saturday-Thursday: 8:00 am - 8:00 pm | ',
    company:'About Us | Career | Community Guidelines ',
    company1: 'Terms & Conditions | Privacy Policy | Contact Us',
    discover: 'News & Articals | How it Works | Earn Money',
    discover1: 'FAQ | Corporate Pitch | Become Service Provider',
    quick_order: 'Quick Order | Find Your Service | Name ',
    quick_order1: ' Phone Number | Comments (if any)',
    more:'Learn More',
    about_us:' WHAT IS | MISTRI MAMA | Mistri Mama is an online based service platform that offers home services in all areas of Dhaka City. We ensure quality service by providing training to our technicians which also emphasis on safety and behavioral aspects. Apart from the domiciliary service, Mistri Mama also provide one-time, periodical subscription for corporate houses. Our highly trained and professional technicians are always a CALL away to provide Electrical, Plumbing, Generator, AC, IT, CCTV, etc. servicing works at your doorstep. We are also open to provide our services during holidays, mid-nights or your free hours.',
    expertise : 'EXPERTISE',
    corporate: 'Corporate',
    b2bpackages: 'B2B Packages',
    contact_form: 'Contact Us | GET IN TOUCH | Full Name ',
    contact_form1: 'Phone * | Company | Email * ',
    contact_form2: 'Message * | Submit',
    unique_benefits : 'Unique Benefits',
    a_us_page : 'About Mistri Mama | Mistri Mama is an online-based service platform that offers home services in all areas of Dhaka City. We ensure quality service by providing training to our technicians which also emphasis safety and behavioral aspects. Apart from the domiciliary service, we also provide a one-time, periodical subscription for corporate houses. Our highly trained and professional technicians are always a CALL away to provide Electrical Services, Plumbing Services, Air Conditioner Services, CCTV Services, IT Services, Generator Services. servicing works at your doorstep. Contact us to request a service through our Mistri Mama webpage, over the phone or social media pages. We are also open to provide our services during holidays/emergency hours / your free hours | Mistri Mama is a sister concern of SSG (Super Star Group), a renowned electrical & electronics conglomerate in Bangladesh, was founded on the principles of harmony, sincerity and pioneering spirit for more than two decades. SSG brand has become synonymous with lifestyle and household electrical products from lighting solutions to electrical accessories, fans to engineering products, properties to renewable energy. The group and its subsidiaries, have had a significant impact on society shaping the future for the 21st century and beyond. The strive for brighter future SSG introduces Mistri Mama',
    a_us_page1 : 'Purpose of Our Service | Technician is a common word in the service industry. But when it comes to an experienced service technician, it is really hard to find. There is no measurement policy to rate them, until you receive the service, experience them. Also, there is a huge question in security measures or the trustworthiness of unknown technicians. Should you let them in your perfect house, or not? To ease up this huge responsibility from your back to find a suitable and experienced service technician, we are here. Mistri Mama is just one call away to make your troubled living perfect.',
    a_us_page2 : 'Our Objective | “Providing quality services with the best customer experience through developing and empowering the local skilled workforce.” | All too often, consumers are forced to deal with appliance repair companies who send rude, inconsiderate, and just plain messy technicians to their homes. But not with Mistri Mama. We know just how awful of an experience that is, and we are committed to being different. That is why you can be confident knowing that when you hire our team, you will be working with technicians who are experts, trustworthy but also who are polite and respectful. Not only do they respect you and your time, but they also respect your home. All of our technicians abide by our commitment to leave no trace behind. In fact, it is our goal to always leave your home in better shape than it was when we arrived. Other than your fixed appliances, you shouldn’t even notice we were there at all!.',
    a_us_page3 : 'What Do We Do | We are providing quality services with the best customer experience through developing and empowering the local skilled workforce. Currently, we are offering a variety of services udder six (6) major services. They are;',
    a_us_page4 : 'Air Conditioner Services | Electrical Services | Plumbing Services ',
    a_us_page5 : 'IT Services | CCTV Services | Generator Services',
    a_us_page6 : 'When a service is required, the user can visit the Mistri Mama website, call us on call center number or knock us on social media pages to get the service. Mistri Mama respect your time more than anything. In fact, we promise we will always show up on time for your scheduled appointment and that we will deliver service that is fast, efficient, and detail-oriented. To take it a step further, the experts who arrive at your door will be wearing clean attire and will have an ID badge on them',
    a_us_page7 : 'Why Choose Us | Why else should you work with Mistri Mama technicians instead of regular technicians? Because we care. We care about your time, your privacy, your appliances. Mistri Mama knows how much you rely on those machines every day to keep your home in working order, and we are committed to helping you get your house running smoothly again. However, we also know that who you hire to come to fix your appliances is equally important. That is why we are so proud to have expert technicians on our team. We provide fast, efficient services that pay attention to the details and get your appliances to prime condition. | We provide our services at your desired time. Which means any convenient time that the user demands. Holiday, late-night, even on emergency hours. Our service partners are committed to providing the service at your selected hour. With these services, we offer accurate and valid service charges to our customers. Individual service charges and service detail is given on the website, which clears out all the confusion of what you will get at what price. It reduces all the hustle of price negotiations.',
    a_us_page8 : 'You can expect the following from our qualified experts; | They will be polite and respectful. | They will show up on time.',
    a_us_page9 : 'They will be clean and in uniform. | They will leave no trace behind. | They are confident and that is why we guarantee all our services.',
    a_us_page10 : 'Contact us to book your service (www.mistrimama.com ‘or’ 09610222111).',
    a_us_page11 : '50 | Trained External Technician | With 150+ assistants',
    a_us_page12 : '23 | Skilled in-house Technician | With assistants',
    a_us_page13 : '6 | B.SC. Engineers | with service experience',
    a_us_page14 : '8 | Diploma Engineers | with years of experience',
    price: 'Price | Starting Price | % Off',
    order_summary :'Order Summary | Back | NEXT',
    use_promo: 'Use promo code here | Use promo code | confirm',
    stepper:'Service Selection | Schedule Time | Confirmation',
    stepper_footer : 'Total Price | Total Service Qty | CANCEL',
    btn:'Cancel | OK | NEXT',
    btn2: 'Remove | Add | Confirm',
    extra_charge: 'Other\'s Charge | For emergency service hour | For Outside City charge',
    qty: 'qty',
    how_it_work:'How It Works | Tell Us What To Do | Order any service of Mistri Mama is a quick and easy task with few clicks. Select a service category, select sub services, select service quantity, select date &amp; time then confirm the order by providing contact number and address.',
    how_it_work1:'If you want to do it more quicker, just call to | 09610-222-111 | and tell how can we help.',
    how_it_work2:'Confirm & Agree | Once you are done with order a service, our customer manager instantly calls you and asks a few questions to collect more details about the service. Upon the consent, customer manager confirms and schedules the service accordingly. | Relax',
    how_it_work3:'What next? Nothing! Now, relax and enjoy Mistri Mama Services.',
    earn_money: 'Refer and Get Paid | Are you a social magnet? Earn some money by telling your friends or family about Mistri Mama services. | Get started by creating a Mistri Mama user account. Spread the word by sharing your unique referral code or referral link through blog posts, articles, emails, Facebook posts and tweets. You’ll get paid for every single service completion through your referral code or referral link',
    earn_money1: 'Why Refer us? | Anyone can participate | Easy and hustle free refer process',
    earn_money2: 'Referrer get reward point by every successful refer | Referrer can use this points to get discount on Mistri Mama services | Referrer can also convert this point to cash',
    earn_money3: 'Referrer can also convert this point to cash | Easy and fast cash out process | How to Earn Money',
    earn_money4: 'Become a Referrer | It\'s easy and free to join. Just register with your name, mobile number and valid Mobile banking number to get start from today. Mobile banking number is required for cash out process. | Refer Someone',
    earn_money5: 'Start sharing referral code or the referral link to others, who is looking for a service. Referrer can share his/her refer code or the referral link to any User through social media or a simple SMS. | Earn Reward Point | User can avail any Mistri Mama service by using the referral code or the link. For every successful service completion, referrer will receive 30% reward points of the actual bill in his/her accounts.',
    earn_money6: 'Get Paid | Referrer can convert his/her earned reward points into cash and easily cash out through his/her enlisted mobile banking number. To cash out referrer will require 600 reward points. | Reward Point Policy',
    earn_money7: 'Referrer will get 30% of RP (reward point) of each successful referred service’s payable amount. (e.g.- Mr. X referred AC detergent service, BDT 1000 to Mr. Y. After successful service, Mr. X will get 30% or 300 reward point). 3 reward points is equivalent to BDT 1. Referrer can withdraw his/her amount, if he/she has minimum 600 reward points, which is equivalent to BDT 200. User or referrer can make service payment through reward point. Only half of total service amount can be adjusted through reward point. | ',
    earn_money8: 'Full Name * | Phone * | Area *',
    earn_money9: 'Select Service * | MFS number * | email',
    bservice_provider: 'Provider | Become Service Provider | GROW YOUR BUSINESS ',
    bservice_provider1: 'Our commitment to deliver superior service to our clients can only be achieved through partnerships with highly-skilled service providers. Service providers who share our passion for quality, honesty and reliability are rewarded with opportunities for more business. | Mistri Mama is growing rapidly, managing services for companies across the Dhaka. We are always looking for qualified service providers in many trades including AC services, Electrical services, Plumbing services, IT services, CCTV services and Generator services. Our goal is to help you grow your business by offering predictable work in your local service area. | GET STARTED ',
    bservice_provider2: 'To get started, complete the information located on the right side of this page. If you’d like to learn more about Mistri Mama contact us at 09610 222 111 | Thank you for your interest in Mistri Mama. | ',
    bservice_provider_from : 'Service Category * | Other Services',
    career: 'A passionate team of employees is the foundation of a successful startup. They become natural advocates and work tirelessly to see the shared company vision come to life. As in life, anything that starts with a weak foundation will struggle to grow. If you have the passion to contribute a growing startup than join with us. To set new standards of ethics and excellence in delivering to our customers superior quality and value-for-money residential and commercial spaces by employing a team of highly motivated and focused professionals. | Open Positions | >We’re looking for people to join the team who are as excited as we are to help build the platform that empowers the future generation of creators to be successful online | ',
    career1: 'Marketing & Business Development | Operation | Call Center',
    career2: 'Technician | Sales | Account & Finance',
    career3: 'Check Opportunity & Apply |  | ',
    career_form: 'Full Name * | Phone Number * | Email *',
    career_form1: 'Year Of Experience | Position * | Salary Expectation',
    career_form2: 'Website/LinkedIn/Portfolio link | Upload File * |  ',
    career_form3: 'Tell us why you want to work for mistrimama | Tell us why you want to work for mistrimama | Submit ',
    ownservice: ' Under | Service bits | ',
    ownservice1: ' Price | Discounted Price | ',
    ownservice2: ' Confirm Your Order | Order Summary | Order Informations',
    ownservice_from: 'Name | Phone Number | Area',
    ownservice_from1: 'Address | Write down your address | Comments',
    ownservice3: ' Total Price | Total Service Qty | ',
    ownservice4: ' Other\'s Charge | For emergency service hour | ',
    data: [
    {
      "id": 6,
      "name": "AC Services",
      "slug": "ac",
      "thumb": "https://staging.mistrimama.com/backend/upload/categories/1597303564749.jpg",
      "icon": "https://staging.mistrimama.com/backend/upload/categories/1597303564768.jpg",
      "opt_image": "https://staging.mistrimama.com/backend/upload/categories/1597303564586.jpg",
      "description": "<p>We repair, So Don’t Despair. For any type of commercial or residential Air Conditioner repairing and maintenance service, call Mistri Mama and get It fixed by the best experts in your area. You never need to carry your Air Conditioner to the mechanics. As our experts, will fix It in your home and they will carry It to the service center If It Is needed. Soon after getting the call or order from the online platform, respective persons will be sent to your home as soon as possible.</p>",
      "benifits": "<ul><li>Provide service at a specific time.</li><li>Providing service by experienced technicians.</li><li>Completely safe and reliable.</li><li>Seven-day service warranty.</li></ul>",
    }
    ]
  },
  bn: {
    welcome_message: 'স্বাগতম',
    thankyou_message:'dhonnobad',
    menu: 'হোম | সেবাসমূহ | আমাদের-সম্পর্কে',
    menu2: 'অর্ডার | যোগাযোগ করুন | লগইন',
    menu3: 'লগআউট | সাইন আপ ',
    footer: 'মিস্ত্রি মামা অফিস  | সেবা | প্রতিষ্ঠান ',
    footer1: 'আবিষ্কার',
    address: 'প্রধান কার্যালয়: ইউসিইপি চেইন টাওয়ার (তৃতীয় তল), ২৫, সেগুনবাগিচা, রমনা,  ঢাকা, পিও: ১০০০ | ব্যবসায়িক অফিস: স্কাই ভিউ ওশান টাওয়ার (প্রথম তল), 38 সেগুনবাগিচা, ঢাকা, বাংলাদেশ ',
    phone:'৮৮০৯৬১০—২২২—১১১',
    Office_time: 'শনিবার-বৃহস্পতিবার: সকাল :৮:০০ টা - রাত ৮:০০ টা | ',
    company:'আমাদের সম্পর্কে | কর্মজীবন | সম্প্রদায় নির্দেশিকা  ',
    company1: 'শর্তাবলী | গোপনীয়তা নীতি  | যোগাযোগ করুন',
    discover: 'সংবাদ & প্রবন্ধ | কিভাবে এটা কাজ করে | অর্থ উপার্জন করা',
    discover1: 'প্রশ্ন | কর্পোরেট পিচ | পরিষেবা সরবরাহকারী হয়ে উঠুন ',
    quick_order: 'দ্রুত অর্ডার | আপনার পরিষেবাটি সন্ধান করুন | নাম  ',
    quick_order1: 'ফোন নম্বর | মন্তব্য (যদি থাকে) ',
    more:'আরও জানুন ',    
    about_us:' মিস্ত্রি মামা | কী | মিস্ত্রি মামা একটি অনলাইন ভিত্তিক পরিষেবা প্ল্যাটফর্ম যা Dhakaাকা শহরের সমস্ত অঞ্চলে হোম সার্ভিস সরবরাহ করে। আমরা আমাদের প্রযুক্তিবিদদের প্রশিক্ষণ প্রদানের মাধ্যমে মানের পরিষেবা নিশ্চিত করি যা সুরক্ষা এবং আচরণগত দিকগুলিতেও জোর দেয়। আঞ্চলিক পরিষেবা ছাড়াও মিস্ত্রি মামা কর্পোরেট হাউসগুলির জন্য এককালীন, পর্যায়ক্রমে সাবস্ক্রিপশন সরবরাহ করে। আমাদের উচ্চ প্রশিক্ষিত এবং পেশাদার প্রযুক্তিবিদগণ আপনার দোরগোড়ায় সার্ভিসিংয়ের কাজগুলি সরবরাহ করতে বৈদ্যুতিক, নদীর গভীরতানির্ণয়, জেনারেটর, এসি, আইটি, সিসিটিভি ইত্যাদির জন্য সর্বদা একটি কল দূরে থাকে। আমরা ছুটি, মধ্যরাত বা আপনার নিখরচায় আমাদের পরিষেবা প্রদানের জন্যও উন্মুক্ত।',
    expertise : 'অভিজ্ঞতা',
    corporate: 'কর্পোরেট',
    b2bpackages: 'বি ২ বি প্যাকেজগুলি',
    contact_form: 'যোগাযোগ করুন | স্পর্শ পেতে | পুরো নাম ',
    contact_form1: 'ফোন * | প্রতিষ্ঠান | ইমেল * ',
    contact_form2: ' বার্তা * | জমা দিন',
    unique_benefits : 'অনন্য সুবিধা',
    a_us_page : 'মিস্ত্রি মামা সম্পর্কে | মিস্ত্রি মামা একটি অনলাইন নির্ভর সার্ভিস প্ল্যাটফর্ম ঢাকা সিটি সব এলাকায় অফার বাড়িতে সেবা। আমরা আমাদের প্রযুক্তিবিদদের প্রশিক্ষণ প্রদানের মাধ্যমে মানের পরিষেবা নিশ্চিত করি যা সুরক্ষা এবং আচরণগত দিকগুলিকেও জোর দেয়। আঞ্চলিক পরিষেবা ছাড়াও, আমরা কর্পোরেট ঘরগুলির জন্য এককালীন, পর্যায়ক্রমে সাবস্ক্রিপশন সরবরাহ করি। আমাদের উচ্চ প্রশিক্ষিত এবং পেশাদার প্রযুক্তিবিদরা বৈদ্যুতিক পরিষেবা, নদীর গভীরতানির্ণয় পরিষেবা, এয়ার কন্ডিশনার পরিষেবাদি, সিসিটিভি পরিষেবাদি, আইটি পরিষেবা, জেনারেটর পরিষেবাদি সরবরাহের জন্য সর্বদা একটি কল দূরে। সার্ভিসিং আপনার দোরগোড়ায় কাজ করে। ফোন এবং সোশ্যাল মিডিয়া পৃষ্ঠাগুলিতে, আমাদের মিস্ত্রি মামা ওয়েবপেজের মাধ্যমে একটি পরিষেবার জন্য অনুরোধ করতে আমাদের সাথে যোগাযোগ করুন। আমরা ছুটি / জরুরী সময় / আপনার ফ্রি সময়কালে আমাদের পরিষেবাগুলি সরবরাহ করার জন্যও উন্মুক্ত | মিস্ত্রি মামা এসএসজি (সুপার স্টার গ্রুপ) এর এক বোন উদ্বেগ, বাংলাদেশের খ্যাতিমান বৈদ্যুতিন ও ইলেকট্রনিক্স সংহতি, দুই দশকেরও বেশি সময় ধরে সম্প্রীতি, আন্তরিকতা এবং অগ্রণী চেতনার নীতিগুলিতে প্রতিষ্ঠিত। এসএসজি ব্র্যান্ডটি বৈদ্যুতিন আনুষাঙ্গিকগুলি থেকে আলো সমাধান থেকে শুরু করে ইঞ্জিনিয়ারিং পণ্যগুলিতে, পুনর্নবীকরণযোগ্য শক্তির বৈশিষ্ট্যগুলিতে লাইফস্টাইল এবং পরিবারের বৈদ্যুতিক পণ্যগুলির সমার্থক হয়ে উঠেছে। এই গোষ্ঠী এবং এর সহায়ক সংস্থাগুলি একবিংশ শতাব্দী এবং তারও পরে সমাজকে ভবিষ্যতের গঠনে উল্লেখযোগ্য প্রভাব ফেলেছে। উজ্জ্বল ভবিষ্যতের এসএসজি মিস্ট্রি মামাকে পরিচয় করিয়ে দেয় ',
    a_us_page1 : 'আমাদের পরিষেবাটির উদ্দেশ্য | প্রযুক্তিবিদ সেবা শিল্প একটি সাধারণ শব্দ। কিন্তু যখন এটি কোনও অভিজ্ঞ সার্ভিস টেকনিশিয়ানদের কাছে আসে, এটি খুঁজে পাওয়া সত্যিই কঠিন। এগুলি রেট করার জন্য কোনও পরিমাপের নীতি নেই, যতক্ষণ না আপনি পরিষেবাটি গ্রহণ করেন, সেগুলি অভিজ্ঞতা না করে। এছাড়াও, সুরক্ষা ব্যবস্থা বা অজানা প্রযুক্তিবিদদের বিশ্বাসযোগ্যতা নিয়ে একটি বিশাল প্রশ্ন রয়েছে। আপনি তাদের আপনার নিখুঁত বাড়িতে রাখা উচিত, না? আপনার পিছন থেকে উপযুক্ত এবং অভিজ্ঞ পরিষেবা প্রযুক্তিবিদ খুঁজতে এই বিশাল দায়িত্বটি সহজ করার জন্য, আমরা এখানে আছি। মিস্ত্রি মামা আপনার সমস্যাবিহীন জীবনযাপনকে নিখুঁত করার জন্য কেবল একটি কল এসেছে। ',
    a_us_page2 : 'আমাদের উদ্দেশ্য | "স্থানীয় দক্ষ জনশক্তিকে বিকাশ ও ক্ষমতায়নের মাধ্যমে সেরা গ্রাহকের অভিজ্ঞতার সাথে মানসম্পন্ন পরিষেবা সরবরাহ করা।" | প্রায়শই প্রায়শই গ্রাহকরা তাদের সরঞ্জাম মেরামতকারী সংস্থাগুলি মোকাবেলা করতে বাধ্য হন যারা তাদের বাড়িতে অসভ্য, ছদ্মবেশী এবং কেবল সরল অগোছালো প্রযুক্তিবিদদের পাঠান। তবে মিস্ত্রি মামার সাথে নয়। আমরা জানি যে অভিজ্ঞতাটি কতটা ভয়াবহ এবং আমরা আলাদা হতে প্রতিশ্রুতিবদ্ধ। এ কারণেই আপনি আত্মবিশ্বাসের সাথে জেনে রাখতে পারেন যে আপনি যখন আমাদের দল নিয়োগ করবেন, আপনি এমন প্রযুক্তিবিদদের সাথে কাজ করবেন যারা বিশেষজ্ঞ, বিশ্বাসযোগ্য তবে ভদ্র ও শ্রদ্ধাশীল। তারা কেবল আপনাকে এবং আপনার সময়কেই সম্মান করে না, তারা আপনার বাড়িকেও সম্মান করে। আমাদের প্রযুক্তিবিদরা সকলেই কোনও চিহ্ন অনুসরণ না করার প্রতিশ্রুতি মেনে চলেন। বাস্তবে, আমরা পৌঁছে যাবার চেয়ে আপনার বাড়িটি সবসময় আরও ভাল আকারে ছেড়ে চলে যাওয়া আমাদের লক্ষ্য। আপনার স্থির সরঞ্জামগুলি ব্যতীত অন্যদিকেও আপনি খেয়াল করবেন না যে আমরা সেখানে ছিলাম না!',
    a_us_page3 : 'আমরা কী করব | আমরা স্থানীয় দক্ষ কর্মীশক্তিকে বিকাশ ও ক্ষমতায়নের মাধ্যমে সেরা গ্রাহকের অভিজ্ঞতার সাথে মানসম্পন্ন পরিষেবা সরবরাহ করছি। বর্তমানে, আমরা ছয় (6) প্রধান সেবা পশুচুচুক বিভিন্ন পরিষেবা প্রস্তাব করা হয়। তারা হয়;',
    a_us_page4 : ' এয়ার কন্ডিশনার সার্ভিস | বৈদ্যুতিক পরিষেবা | প্লাম্বিং সেবা',
    a_us_page5 : ' আইটি পরিষেবাদি | সিসিটিভি পরিষেবাদি | জেনারেটর পরিষেবা ',
    a_us_page6 : ' যখন কোনও পরিষেবার প্রয়োজন হয়, ব্যবহারকারী মিস্ত্রি মামা ওয়েবসাইটটি দেখতে পারেন, কল সেন্টার নম্বরে কল করতে পারেন বা পরিষেবাটি পেতে সোশ্যাল মিডিয়া পৃষ্ঠাগুলিতে আমাদের নক করতে পারেন। মিস্ত্রি মামা আপনার সময়কে যে কোনও কিছুর চেয়ে বেশি সম্মান করেন। প্রকৃতপক্ষে, আমরা প্রতিশ্রুতি দিয়েছি যে আমরা আপনার নির্ধারিত অ্যাপয়েন্টমেন্টের জন্য সর্বদা সময়মতো উপস্থিত থাকব এবং আমরা দ্রুত, দক্ষ এবং বিশদ-ভিত্তিক পরিষেবাটি সরবরাহ করব। এটি আরও একধাপ এগিয়ে নিয়ে যাওয়ার জন্য, আপনার দরজায় যে বিশেষজ্ঞরা আগমন করবেন তারা পরিচ্ছন্ন পোশাক পরবেন এবং তাদের উপর একটি আইডি ব্যাজ থাকবে',
    a_us_page7 : 'কেন আমাদের নির্বাচন করেছে | কেন আপনি নিয়মিত প্রযুক্তিবিদদের পরিবর্তে মিস্ত্রি মামা প্রযুক্তিবিদদের সাথে কাজ করবেন? কারণ আমরা যত্নশীল। আমরা আপনার সময়, আপনার গোপনীয়তা, আপনার সরঞ্জাম সম্পর্কে যত্নশীল। মিস্ত্রি মামা জানেন যে আপনি প্রতিদিন আপনার বাড়িকে কাজের শৃঙ্খলা রক্ষার জন্য। মেশিনগুলিতে কতটা নির্ভরশীল এবং আমরা আপনাকে আবার আপনার ঘরটি সুচারুভাবে চালাতে সহায়তা করতে প্রতিশ্রুতিবদ্ধ। তবে আমরা এটাও জানি যে আপনি যাকে নিজের সরঞ্জাম ঠিক করতে এসেছেন তাও সমান গুরুত্বপূর্ণ। সে কারণেই আমাদের দলে বিশেষজ্ঞ প্রযুক্তিবিদদের নিয়ে আমরা গর্বিত। আমরা দ্রুত, দক্ষ পরিষেবাগুলি সরবরাহ করি যা বিশদগুলিতে মনোযোগ দেয় এবং আপনার সরঞ্জামগুলি প্রাথমিক অবস্থাতে নিয়ে আসে। | আমরা আপনার কাঙ্ক্ষিত সময়ে আমাদের পরিষেবাগুলি সরবরাহ করি। যার অর্থ ব্যবহারকারী যে কোনও সুবিধাজনক সময়ের দাবি রাখে। ছুটির দিন, গভীর রাত, এমনকি জরুরি সময়েও। আমাদের পরিষেবা অংশীদাররা আপনার নির্বাচিত সময়ে পরিষেবা সরবরাহ করতে প্রতিশ্রুতিবদ্ধ। এই পরিষেবাগুলির সাথে, আমরা আমাদের গ্রাহকদের সঠিক এবং বৈধ পরিষেবা চার্জের অফার করি। পৃথক পরিষেবা চার্জ এবং পরিষেবার বিবরণ ওয়েবসাইটে দেওয়া হয়, যা আপনি কোন দামে কী পাবেন তার সমস্ত বিভ্রান্তি পরিষ্কার করে। এটি দামের আলোচনার সমস্ত হ্রাসকে হ্রাস করে।',
    a_us_page8 : 'আপনি আমাদের যোগ্য বিশেষজ্ঞদের কাছ থেকে নিম্নলিখিতটি আশা করতে পারেন; | তারা নম্র এবং শ্রদ্ধাশীল হবে। | তারা সময়মতো প্রদর্শিত হবে।',
    a_us_page9 : 'তারা পরিষ্কার এবং ইউনিফর্ম হবে। | তারা কোন চিহ্ন অনুসরণ করবে না। | তারা আত্মবিশ্বাসী এবং সে কারণেই আমরা আমাদের সমস্ত পরিষেবার গ্যারান্টি দিচ্ছি।',
    a_us_page10 : 'আপনার পরিষেবা বুক করতে আমাদের সাথে যোগাযোগ করুন (www.mistrimama.com ‘বা’ 09610222111)।',
    a_us_page11 : '৫০ | প্রশিক্ষিত বাহ্যিক প্রযুক্তিবিদ | ১৫০+ সহকারী সহ',
    a_us_page12 : '২৩ | দক্ষ ইন-হাউস টেকনিশিয়ান | সহকারীদের সাথে',
    a_us_page13 : '৬ | বি.এস.সি. প্রকৌশলী | পরিষেবা অভিজ্ঞতার সাথে',
    a_us_page14 : '৮ | ডিপ্লোমা ইঞ্জিনিয়ার্স | অভিজ্ঞতা বছরের সাথে',    
    price: 'মূল্য | প্রারম্ভিক মূল্য | % ছাড়ে',
    order_summary :'অর্ডার সারাংশ | পেছনে | পরবর্তী ',
    use_promo: 'প্রমো এখানে কোড ব্যবহার করুন | ব্যবহারের প্রচার কোড | কন্ফার্ম',
    stepper:'পরিষেবা নির্বাচন | সময়সূচী | নিশ্চিতকরণ',
    stepper_footer : 'মোট দাম | মোট পরিষেবা পরিমাণ | বাতিল',
    btn:'বাতিল | ঠিক আছে | পরবর্তী',
    btn2: 'Remove | Add | Confirm',
    extra_charge: 'অন্যান্য চার্জ | জরুরী পরিষেবা ঘন্টা | বাইরের সিটি চার্জের জন্য ',
    qty:'পরিমাণ',
    how_it_work:'এটি কীভাবে কাজ করে | আমাদের কী বলুন | মিস্ট্রি মামার যে কোনও পরিষেবা অর্ডার করুন কয়েকটি ক্লিক সহ একটি দ্রুত এবং সহজ কাজ। একটি পরিষেবা বিভাগ নির্বাচন করুন, উপ-পরিষেবাগুলি নির্বাচন করুন, পরিষেবার পরিমাণ নির্বাচন করুন, তারিখ নির্বাচন করুন & সময় তারপরে যোগাযোগের নম্বর এবং ঠিকানা সরবরাহ করে অর্ডারটি নিশ্চিত করুন।',
    how_it_work1:'আপনি যদি এটি আরও দ্রুত করতে চান তবে কেবল কল করুন | 09610-222-111 | এবং বলুন আমরা কীভাবে সহায়তা করতে পারি।',
    how_it_work2:'নিশ্চিত করুন এবং সম্মত হন | আপনি যখন কোনও পরিষেবা অর্ডার দিয়ে শেষ করেন, আমাদের গ্রাহক ম্যানেজার তাত্ক্ষণিকভাবে আপনাকে কল করে এবং পরিষেবা সম্পর্কে আরও বিশদ সংগ্রহ করার জন্য কয়েকটি প্রশ্ন জিজ্ঞাসা করে। সম্মতিতে, গ্রাহক ম্যানেজার নিশ্চিত করে পরিষেবা অনুসারে সময়সূচি দেয়। | আরাম করুন',
    how_it_work3:'এরপর কী? কিছুই না! এখন, শিথিল করুন এবং মিস্ত্রি মামা পরিষেবাদিগুলি উপভোগ করুন।',
    earn_money: 'রেফার করুন এবং বেতন পান | আপনি কি সামাজিক চৌম্বক? আপনার বন্ধু বা পরিবারকে মিস্ত্রি মামা পরিষেবাদি সম্পর্কে কিছু অর্থ উপার্জন করুন। | মিস্ত্রি মামা ব্যবহারকারী অ্যাকাউন্ট তৈরি করে শুরু করুন। ব্লগ পোস্ট, নিবন্ধ, ইমেল, ফেসবুক পোস্ট এবং টুইটের মাধ্যমে আপনার অনন্য রেফারেল কোড বা রেফারেল লিঙ্কটি ভাগ করে শব্দটি ছড়িয়ে দিন। আপনার রেফারেল কোড বা রেফারেল লিঙ্কের মাধ্যমে প্রতিটি একক পরিষেবার সমাপ্তির জন্য আপনাকে অর্থ প্রদান করা হবে',
    earn_money1: 'আমাদের রেফার করুন কেন? | যে কেউ অংশ নিতে পারেন | সহজ এবং তাড়াতাড়ি ফ্রি রেফার প্রক্রিয়া',
    earn_money2: 'রেফারার প্রতিটি সফল রেফারেন্স দ্বারা পুরষ্কার পয়েন্ট পাবেন | রেফারার মিস্ট্রি মামা পরিষেবাদিতে ছাড় পেতে এই পয়েন্টগুলি ব্যবহার করতে পারেন | রেফারারও এই বিন্দুকে নগদ রূপান্তর করতে পারে',
    earn_money3: 'রেফারারও এই বিন্দুকে নগদ রূপান্তর করতে পারে | সহজ এবং দ্রুত নগদ আউট প্রক্রিয়া | কীভাবে অর্থ উপার্জন করবেন ',
    earn_money4: 'একটি রেফারার হন | এটি যোগ করা সহজ এবং নিখরচায়। আজ থেকে শুরু করতে কেবল নিজের নাম, মোবাইল নম্বর এবং বৈধ মোবাইল ব্যাংকিং নম্বর দিয়ে নিবন্ধন করুন। নগদ আউট প্রক্রিয়াটির জন্য মোবাইল ব্যাংকিং নম্বর প্রয়োজন। | কাউকে রেফার করুন ',
    earn_money5: 'রেফারেল কোড বা অন্যের সাথে রেফারেল লিঙ্ক ভাগ করে নেওয়া শুরু করুন, যারা কোনও পরিষেবা খুঁজছেন। রেফারার তার / তার রেফারেল কোড বা রেফারেল লিঙ্কটি যে কোনও ব্যবহারকারীর সাথে সোশ্যাল মিডিয়া বা একটি সাধারণ এসএমএসের মাধ্যমে ভাগ করতে পারে।  | পুরষ্কার পয়েন্ট উপার্জন করুন | ব্যবহারকারী রেফারেল কোড বা লিঙ্কটি ব্যবহার করে যে কোনও মিস্ত্রি মামা পরিষেবা পেতে পারেন। প্রতিটি সফল পরিষেবা সমাপ্তির জন্য, রেফারার তার অ্যাকাউন্টগুলিতে আসল বিলের ৩০% পুরষ্কার পয়েন্ট পাবেন। ',
    earn_money6: 'অর্থ প্রদান করা | রেফারার তার উপার্জিত পুরষ্কার পয়েন্টগুলিকে নগদে রূপান্তর করতে পারে এবং সহজেই তার তালিকাভুক্ত মোবাইল ব্যাংকিং নম্বরের মাধ্যমে নগদ আউট করতে পারে। রেফারারের নগদ অর্থ গ্রহণের জন্য ৬০০ টি পুরষ্কার পয়েন্ট প্রয়োজন হবে . | পুরষ্কার পয়েন্ট নীতি ',
    earn_money7: 'রেফারার প্রতিটি সফল রেফার্ড পরিষেবার প্রদেয় পরিমাণের ৩০% আরপি (পুরষ্কার পয়েন্ট) পাবে। (উদাঃ- মিঃ এক্স রেজিস্টার এসি ডিটারজেন্ট পরিষেবা, মিঃ ওয়াইয়ের কাছে ১০০০ টাকা) সাফল্যের পরে, মিঃ এক্স ৩০% বা ৩০০ পুরষ্কার পয়েন্ট পাবেন) ৩ পুরস্কার পয়েন্ট টাকা 1. রেফারার সমতূল্য যদি তিনি / সে ন্যূনতম ৬০০ পুরস্কার পয়েন্ট, যা টাকা ২০০. ইউজার বা রেফারার পুরস্কার বিন্দুর মধ্য দিয়ে সেবা প্রদান করতে পারেন সমতূল্য আছে, তাঁর / তার পরিমাণ প্রত্যাহার করতে পারবেন। মোট পরিষেবার পরিমাণের অর্ধেকই পুরষ্কার পয়েন্টের মাধ্যমে সামঞ্জস্য করা যায় ',
    earn_money8: 'পুরো নাম  * | ফোন  * | ক্ষেত্রফল  *',
    earn_money9: 'পরিষেবা নির্বাচন করুন  * | এমএফএস নম্বর  * | ইমেল ',
    bservice_provider: 'সরবরাহকারী | পরিষেবা সরবরাহকারী হয়ে উঠুন | আপনার ব্যবসা বৃদ্ধি করুন ',
    bservice_provider1: 'আমাদের ক্লায়েন্টদের উচ্চতর পরিষেবা সরবরাহের আমাদের প্রতিশ্রুতি শুধুমাত্র উচ্চ দক্ষ পরিষেবা প্রদানকারীদের সাথে অংশীদারিত্বের মাধ্যমেই অর্জন করা যেতে পারে। পরিষেবা, সরবরাহকারী যারা গুণমান, সততা এবং নির্ভরযোগ্যতার জন্য আমাদের আবেগ ভাগ করে তাদের আরও ব্যবসায়ের সুযোগের সাথে পুরস্কৃত করা হয় | মিস্ত্রি মামা, দ্রুত বর্ধনশীল হয় ঢাকা জুড়ে কোম্পানীর জন্য সেবা পরিচালনার। আমরা সবসময় এসি পরিষেবাদি, বৈদ্যুতিক পরিষেবা, নদীর গভীরতানির্ণয় পরিষেবা, আইটি পরিষেবা, সিসিটিভি পরিষেবা এবং জেনারেটর পরিষেবা সহ অনেক ব্যবসায় যোগ্য সেবা প্রদানকারীদের সন্ধান করি। আমাদের লক্ষ্য আপনার স্থানীয় পরিষেবা অঞ্চলে পূর্বাভাসযোগ্য কাজের প্রস্তাব দিয়ে আপনার ব্যবসায় বাড়াতে সহায়তা করা | এবার শুরু করা যাক ',
    bservice_provider2: 'শুরু করতে, এই পৃষ্ঠার ডানদিকে অবস্থিত তথ্য সম্পূর্ণ করুন। আপনি যদি মিস্ত্রি মামা সম্পর্কে আরও জানতে চান তবে আমাদের সাথে ০৯৬১০ ২২২ ১১১ এ যোগাযোগ করুন | মিস্ত্রি মামা আপনার আগ্রহের জন্য আপনাকে ধন্যবাদ | ',
    bservice_provider_from : 'পরিষেবা বিভাগ * | অন্যান্য সেবা ',
    career: 'কর্মীদের একটি উত্সাহী দল একটি সফল স্টার্টআপের ভিত্তি। তারা প্রাকৃতিক উকিল হয়ে ওঠেন এবং অংশীদারি সংস্থার দৃষ্টিভঙ্গি জীবনে আসার জন্য অক্লান্ত পরিশ্রম করেন। জীবনের মতো, দুর্বল ভিত্তি দিয়ে শুরু হওয়া যে কোনও কিছুই বৃদ্ধি পেতে লড়াই করবে। আপনার সাথে আমাদের যোগদানের চেয়ে বর্ধমান সূচনায় অবদান রাখার আবেগ থাকলে। অত্যন্ত অনুপ্রাণিত এবং মনোনিবেশিত পেশাদারদের একটি দল নিয়োগ করে আমাদের গ্রাহকদের উন্নতমানের এবং মূল্যবান অর্থের জন্য আবাসিক এবং বাণিজ্যিক স্থানগুলি প্রদানের ক্ষেত্রে নৈতিকতা এবং শ্রেষ্ঠত্বের নতুন মান নির্ধারণ করা। | ওপেন পজিশন | আমরা এমন দলে যোগদানের জন্য লোকদের সন্ধান করছি যারা আমাদের মতো প্ল্যাটফর্মটি তৈরি করতে সহায়তা করতে পারে যা ভবিষ্যতের প্রজন্মের স্রষ্টাদের অনলাইনে সফল হতে সহায়তা করে',
    career1: 'বিপণন ও ব্যবসায় উন্নয়ন | অপারেশন | কল সেন্টার',
    career2: 'টেকনিশিয়ান | বিক্রয় | অ্যাকাউন্ট এবং ফিনান্স ',
    career3: 'সুযোগ পরীক্ষা করুন এবং প্রয়োগ করুন  |  | ',
    career_form: 'পুরো নাম * | ফোন নম্বর * | ইমেল  *',
    career_form1: 'অভিজ্ঞতার বছর | অবস্থান * | বেতন প্রত্যাশা ',
    career_form2: 'ওয়েবসাইট / লিংকডইন / পোর্টফোলিও লিঙ্ক | ফাইল আপলোড করুন * | ',
    career_form3: 'আপনি কেন মিস্রি মামার হয়ে কাজ করতে চান | আপনি কেন মিস্রি মামার হয়ে কাজ করতে চান | জমা দিন ',
    ownservice: ' অধীনে | পরিষেবা বিট | ',
    ownservice1: ' দাম | মূল্য ছাড় | ',
    ownservice2: ' আপনার আদেশ নিশ্চিত করুন | আদেশ তথ্য | অর্ডার সারাংশ ',
    ownservice_from: 'নাম  | ফোন নম্বর  | অঞ্চল ',
    ownservice_from1: 'ঠিকানা  | আপনার ঠিকানা লিখুন  | মন্তব্য ',
    ownservice3: ' মোট দাম  | মোট পরিষেবা পরিমাণ  | ',
    ownservice4: ' অন্যের চার্জ | জরুরী পরিষেবা ঘন্টা জন্য  | ',
    data: [
    {
      "id": 6,
      "name": "AC Services bn",
      "slug": "ac",
      "thumb": "https://staging.mistrimama.com/backend/upload/categories/1597303564749.jpg",
      "icon": "https://staging.mistrimama.com/backend/upload/categories/1597303564768.jpg",
      "opt_image": "https://staging.mistrimama.com/backend/upload/categories/1597303564586.jpg",
      "description": "<p>We repair, So Don’t Despair. For any type of commercial or residential Air Conditioner repairing and maintenance service, call Mistri Mama and get It fixed by the best experts in your area. You never need to carry your Air Conditioner to the mechanics. As our experts, will fix It in your home and they will carry It to the service center If It Is needed. Soon after getting the call or order from the online platform, respective persons will be sent to your home as soon as possible.</p>",
      "benifits": "<ul><li>Provide service at a specific time.</li><li>Providing service by experienced technicians.</li><li>Completely safe and reliable.</li><li>Seven-day service warranty.</li></ul>",
    }
    ]
  }
}

export default messages